# Lang
language: tr

# Header
menu:
  /: /
  Blog: /blog
  Kimdir?: /ayhansipahi
# rss:

# Content
fancybox: false


# Miscellaneous
google_analytics:
favicon: 
twitter: http://x.com/_ayhansipahi
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Ayhan Sipahi
description: _YazÄ±lÄ±m GeliÅŸtirici_
links:
  Blog: /blog
  GitHub: https://github.com/ayhansipahi
  ğ• : https://x.com/_ayhansipahi


# Info
archive_footer_content: test
post_footer_content: test
